apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy
  labels:
    app: autodeploy
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1716919776592
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy
  template:
    metadata:
      labels:
        app: autodeploy
    spec:
      containers:
        - name: autodeploy
          image: acrworkflow1716919776592.azurecr.io/image-workflow-1716919776592:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
